
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 07 08:58:12 VET 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROGRAMA = 14;
  public static final int PUNTOYCOMA = 20;
  public static final int DOSPUNTOS = 19;
  public static final int TIPOENTERO = 22;
  public static final int IGUAL = 12;
  public static final int SUMA = 5;
  public static final int SIGNO = 13;
  public static final int DIVI = 7;
  public static final int MULTI = 8;
  public static final int POTENCIA = 9;
  public static final int NUMEROREAL = 3;
  public static final int ID = 4;
  public static final int COMA = 18;
  public static final int TIPOREAL = 21;
  public static final int FINVAR = 15;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PARENTIZQ = 11;
  public static final int FIN = 17;
  public static final int PARENTDER = 10;
  public static final int NUMEROENTERO = 2;
  public static final int VAR = 16;
  public static final int RESTA = 6;
}

