
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 06 07:39:41 PST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPARENT = 10;
  public static final int POTENCIA = 7;
  public static final int SUMA = 3;
  public static final int ENTERO = 2;
  public static final int MULTIPLICACION = 6;
  public static final int EOF = 0;
  public static final int SIGNO = 11;
  public static final int RESULTADO = 8;
  public static final int error = 1;
  public static final int DIVISION = 5;
  public static final int RESTA = 4;
  public static final int LPARENT = 9;
}

