
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 31 07:47:38 VET 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVI = 5;
  public static final int DIGITO = 2;
  public static final int PARENTDER = 8;
  public static final int POTENCIA = 7;
  public static final int SUMA = 3;
  public static final int MULTI = 6;
  public static final int EOF = 0;
  public static final int SIGNO = 11;
  public static final int IGUAL = 10;
  public static final int error = 1;
  public static final int RESTA = 4;
  public static final int PARENTIZQ = 9;
}

